add matrix algo
HeavyTechRuby/fibonacci pull request #3
Opened 2024-07-23 10:31 UTC by secretpray

2024-07-26 11:32 UTC, sergio-fry commented
@secretpray я могу тебя добавить результаты в README тоже?

2024-07-27 13:13 UTC, secretpray commented
> @secretpray я могу тебя добавить результаты в README тоже?

Привет! Я не против, если эта информация действительно нужна в README)
PR Данный делал больше из любопытства.

2024-07-31 18:06 UTC, sergio-fry requested changes
@secretpray так весь проект, ради интереса. Да, добавь в readme, пожалуйста, чтобы результаты были наглядными

2024-08-01 13:10 UTC, sergio-fry approved these changes

2024-08-01 13:10 UTC, merged